# Generated by Django 5.1.7 on 2025-03-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_product_farmer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='product_qrcodes/'),
        ),
    ]
